### ISSUE TITLE
Banco de imoveis aceitando poucos caracteres

### ISSUE THREAD

**Issue by RempelV** [l-eduardo/Help-Imov#36]
Model de imovel aceita poucos caracteres (36) no campo endereço, aumentar

**Comment by Abmaelbt** [comment]
acho que ja tinha essa issue pra tratar isso: https://github.com/l-eduardo/Help-Imov/issues/15. Vou fechar ela e tratar o problema nessa aqui.

**Comment by Abmaelbt** [comment]
resolvido na branch: `issues_e_ajustes`. Aguardando para ser mergeada na main.
